In [3]:
%%sh
pip install spacy
python -m spacy download en_core_web_md


✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')


✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')


✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')


In [1]:
from utilities import Predict

In [2]:
main = Predict('models/model.joblib')

In [6]:
ss = main.get_embeddings('hi name sohrab')

In [7]:
type(main.model.predict(ss))

numpy.ndarray

numpy.ndarray

numpy.ndarray

In [9]:
str(main.model.predict(ss)[0])

'3'

'3'

'3'

In [37]:
from sklearn.preprocessing import LabelEncoder
import numpy as np

import joblib
import re
import spacy
nlp = spacy.load('en_core_web_md')

class Predict():
    def __init__(self, model_path, encoder_path):
        self.model = self.read_model(model_path)
        self.encoder = self.read_encoder(encoder_path)

    def read_model(self, model_path):
        ''' 
           Function to load a joblib file from a local file
           
               Arguments:
               * path: path to the model
               Outputs:
               * model: loaded joblib model 
        '''
        with open(model_path, 'rb') as f:
            self.model = joblib.load(f)
        return self.model
    
    def read_encoder(self, encoder_path):
        ''' 
           Function to load a the saved sklearn labelencoder
           
               Arguments:
               * path: path to the model
               Outputs:
               * model: loaded joblib model 
        '''
        self.encoder = LabelEncoder()
        self.encoder.classes_ = np.load(encoder_path, allow_pickle=True)
        return self.encoder
    
    
    @staticmethod
    def clean_text(words, remove_list=None):
        '''
        Function to clean text data
        Arguments:
            * remove_list: a list of words that should be removed
        Outputs:
            * cleaned text 
        '''
        if not words:
            return None 

        if remove_list is None:

            remove_list = ["and", "to", "was", "it", "<<<", "into",
                           "a", "i", "with", 'that', ">>>",
                           "would", "with", "of", "[", "]",
                           "in", "he", "on", "*", "n", "at",
                           "for", "we", "y", "had", "or", "ip",
                           "from", "were", "is", "has", "her", "she",
                           "as", "this", "be", "his", "all", "my"
                           , "by", "any", "each", "will", 'a', 's', 'its', 'if', 'are']

        remove_list = remove_list + re.findall(r"<<<\[([^\]\[\r\n]*)\]>>>", words)

        words = str(words)
        words = words.lower()
        words = words.replace("<<<", "")
        words = words.replace(">>>", "")
        words = words.replace("[", "")
        words = words.replace("]", "")
        words = words.replace("(", "")
        words = words.replace(")", "")
        words = words.replace("*", "")
        words = words.replace("what's", "what is ")
        words = words.replace(".", "")
        words = words.replace(",", "")
        words = words.replace("wasn't", "was not")
        words = words.replace("can't", "cannot")
        words = words.replace("it's", "it is")
        words = words.replace("it's", "it is")
        words = words.replace("\'ve", " have ")
        words = words.replace("'s", " ")
        words = words.replace("can't", "cannot ")
        words = words.replace("don't", "do not ")
        words = words.replace("doesn't", "does not ")
        words = words.replace("n't", "not ")
        words = words.replace(r"i'm", "i am")
        words = words.replace(r" m ", " am ")
        words = words.replace(r"\'re", " are ")
        words = words.replace(r"\'d", " would ")
        words = words.replace("'", "")
        words = words.replace("!", "")
        words = words.replace(r"\'ll", " will ")
        words = words.replace(r"´", "")
        words = words.replace("`", "")
        words = words.replace("\r\n", " ")
        words = words.replace("the", "")

        split_out = [x for x in words.split() if x not in remove_list]

        return " ".join(split_out)
    
    @staticmethod
    def get_embeddings(text):
        ''' 
        Function to maps the training dataset to the spacy embeddings
        Arguments:
            * target text
        Outputs:
            * list with embeddings
        '''
        return nlp(text).vector.reshape(1,-1)


In [45]:
input_text = "some text"
main= Predict(model_path = './models/model.joblib',encoder_path =  './models/le_classes.npy')

em = main.get_embeddings(input_text)
predict_result = main.model.predict(em)
model_result = str(predict_result[0])
label = main.encoder.inverse_transform(predict_result)

In [54]:
( main.model.predict_proba(em))[0]

array([0.1141601 , 0.1298457 , 0.07581609, 0.22881781, 0.04021368,
       0.08062302, 0.33052362])

In [61]:
import json 
str((main.model.predict_proba(em))[0])

'[0.1141601  0.1298457  0.07581609 0.22881781 0.04021368 0.08062302\n 0.33052362]'

In [38]:
ss= Predict(model_path = './models/model.joblib',encoder_path =  './models/le_classes.npy')

In [40]:
vec = ss.get_embeddings('hi name sohrab')

In [41]:
ss.model.predict(vec)

array([6])

In [42]:
sss= ss.model.predict(vec)
sss

array([6])

In [43]:
ss.encoder.inverse_transform(sss)

array(['others'], dtype=object)

In [10]:
ss.model.predict_proba(vec)

array([[0.09201951, 0.0743869 , 0.11655098, 0.31863059, 0.03634997,
        0.02107692, 0.34098513]])

In [61]:
ss = Predict.get_embeddings('hi name sohrab')

In [89]:
f = nlp('hi name sohrab').vector.reshape(1,-1)

In [63]:
len(f)

300

In [68]:
rf.predict(f.reshape(1,-1) )

array([3])